name: SonarCloud analysis

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  sonar:
    name: SonarCloud Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Install Dependencies
        id: install
        run: pnpm install

      - name: Test
        id: pnpm-ci-test
        run: pnpm jest --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
